### ISSUE TITLE
Doesnt load "Explore" window

### ISSUE THREAD

**Issue by firefoxlover** [flathub/chat.schildi.desktop#5]
When trying to load the "Explore Rooms" window using the compass icon, it doesnt show the Windows anymore. This worked in previos versions.

Version of SchildiChat: 1.10.12-sc.1
Version of Olm: 3.2.8
Kubuntu 22.04

**Comment by su-ex** [comment]
I'll take a look, maybe this resolved or worsened itself with the latest merge.
However, such issues should go to https://github.com/SchildiChat/schildichat-desktop, as they are not only applicable to the flatpak.

**Comment by su-ex** [comment]
I've tested this on the current latest release and after the latest merge and it's working for both.
Can you elaborate which compass button you mean?

**Comment by su-ex** [comment]
No answer and at the wrong place.
